language: php
php:
  - '7.1'
  - '7.2'

script:
#  - composer self-update
  - composer install --dev
  - ./vendor/bin/phpunit

after_success:
  - chomod +x deploy.sh
  - ./deploy.sh

notifications:
  email: false