language: php
php:
  - '7.1'
  - '7.2'

script:
#  - composer self-update
  - composer install --dev
  - ./vendor/bin/phpunit

after_success:
- curl --ftp-create-dirs
       -T ./
       sftp://${SFTP_USER}:${SFTP_PASSWORD}@${SFTP_HOST}/ugamela

notifications:
  email: false