language: php
php:
  - '7.1'

script:
#  - composer self-update
  - composer install --dev
  - ./vendor/bin/phpunit

after_success:
  - chmod +x deploy.sh
  - ./deploy.sh

notifications:
  email: false