language: php
php:
  - '7.1'
  - '7.2'

env:
  global:
  - 'SFTP_USER=${SFTP_USER}'
  - 'SFTP_PASSWORD=${SFTP_PASSWORD}'

script:
#  - composer self-update
  - composer install --dev
  - ./vendor/bin/phpunit

after_success:
- curl --ftp-create-dirs
       -T filename
       sftp://${SFTP_USER}:${SFTP_PASSWORD}@${SFTP_HOST}/ugamela

notifications:
  email: false