language: php
php:
  - '7.1'

script:
#  - composer self-update
  - composer install --dev
  - ./vendor/bin/phpunit

after_success:
  - php ./vendor/bin/phpdoc -i "css/,images/,scripts/,skins/,tests/,vendor/,core/config.php,test.php" -d ./ --template clean --title "ugamela Documentation"
  - mv output/ docs/
  - rm -rf ./docs/build/
  - curl --ftp-create-dirs -T ./ -u $SFTP_USER:$SFTP_PASSWORD sftp://$SFTP_HOST/ugamela/$f

notifications:
  email: false